config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get 'auth/github/callback', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :users, only: [:index]
  get '/:username', to: 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/create_event.rb
class CreateEvent
  attr_reader :user_avatar,
              :created_at

  def initialize(attrs={})
    @user_avatar = attrs[:actor][:avatar_url]
    @user_name = attrs[:actor][:login]
    @repo_name = attrs[:repo][:name]
    @created_at = attrs[:created_at]
  end

  def summary
    "#{user_name} created a repository #{repo_name}"
  end

  private
    attr_reader :user_name,
                :repo_name
end

app/models/fork_event.rb
class ForkEvent
  attr_reader :user_avatar,
              :created_at

  def initialize(attrs={})
    @user_avatar = attrs[:actor][:avatar_url]
    @user_name = attrs[:actor][:login]
    @repo_name = attrs[:payload][:forkee][:full_name]
    @forkee = attrs[:repo][:name]
    @created_at = attrs[:created_at]
  end

  def summary
    "#{user_name} forked #{repo_name} from #{forkee}"
  end

  private
    attr_reader :user_name,
                :repo_name,
                :forkee
end

app/models/github_user.rb
class GithubUser < SimpleDelegator
  def github_service
    GithubService.new(token)
  end

  def starred_repos
    github_service.get_url('user/starred')
  end

  def recent_commits
    push_events.sum(&:commit_count)
  end

  def recent_repo_commits
    push_events.group_by(&:repo_name).transform_values do |events|
      events.sum(&:commit_count)
    end
  end

  def activity_events
    github_service.get_url("users/#{nickname}/received_events").map do |event|
      case event[:type]
      when 'MemberEvent' then MemberEvent.new(event)
      when 'CreateEvent' then CreateEvent.new(event)
      when 'WatchEvent' then WatchEvent.new(event)
      when 'ForkEvent' then ForkEvent.new(event)
      end
    end
  end

  def repos
    github_service.get_url("user/repos?per_page=100").map do |raw_repo|
      Repo.new(raw_repo)
    end
  end

  def pinned_repos
    repos.first(6)
  end

  def organizations
    github_service.get_url("users/#{nickname}/orgs").map do |org|
      Organization.new(org) if org
    end
  end

  private
    def push_events
      get_push_events.map do |raw_event|
        PushEvent.new(raw_event)
      end
    end

    def get_push_events
      github_service.get_url("users/#{nickname}/events").find_all do |event|
        event[:type] == 'PushEvent'
      end
    end
end

app/models/member_event.rb
class MemberEvent
  attr_reader :user_avatar,
              :created_at

  def initialize(attrs={})
    @user_avatar = attrs[:actor][:avatar_url]
    @user_name = attrs[:actor][:login]
    @action = attrs[:payload][:action]
    @member = attrs[:payload][:member][:login]
    @repo_name = attrs[:repo][:name]
    @created_at = attrs[:created_at]
  end

  def summary
    "#{user_name} #{action} #{member} to #{repo_name}"
  end

  private
    attr_reader :user_name,
                :action,
                :member,
                :repo_name
end

app/models/organization.rb
class Organization
  attr_reader :name,
              :avatar_url

  def initialize(attrs={})
    @name = attrs[:login]
    @avatar_url = attrs[:avatar_url]
  end
end

app/models/push_event.rb
class PushEvent
  attr_reader :created_at, :repo_name, :commit_count

  def initialize(attrs={})
    @created_at = attrs[:created_at]
    @repo_name = attrs[:repo][:name]
    @commit_count = attrs[:payload][:commits].count
  end
end

app/models/repo.rb
class Repo
  attr_reader :name,
              :language,
              :html_url,
              :forks_count,
              :fork,
              :updated_at

  def initialize(attrs={})
    @name = attrs[:name]
    @html_url = attrs[:html_url]
    @language = attrs[:language]
    @forks_count = attrs[:forks_count]
    @fork = attrs[:fork]
    @updated_at = attrs[:updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.update_or_create(auth)
    user = User.find_or_create_by(uid: auth[:uid])
    user.update(
      uid: auth[:uid],
      email: auth[:info][:email],
      nickname: auth[:info][:nickname],
      name: auth[:info][:name],
      image: auth[:info][:image],
      location: auth[:extra][:raw_info][:location],
      bio: auth[:extra][:raw_info][:bio],
      repo_count: auth[:extra][:raw_info][:public_repos] + auth[:extra][:raw_info][:total_private_repos],
      follower_count: auth[:extra][:raw_info][:followers],
      following_count: auth[:extra][:raw_info][:following],
      token: auth[:credentials][:token]
    )
    user
  end
end

app/models/watch_event.rb
class WatchEvent
  attr_reader :user_avatar,
              :created_at

  def initialize(attrs={})
    @user_name = attrs[:actor][:login]
    @user_avatar = attrs[:actor][:avatar_url]
    @repo_name = attrs[:repo][:name]
    @action = attrs[:payload][:action]
    @created_at = attrs[:created_at]
  end

  def summary
    "#{user_name} #{action} watching #{repo_name}"
  end

  private
    attr_reader :user_name,
                :repo_name,
                :action

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(uid: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['omniauth.auth']
    user = User.update_or_create(auth)
    redirect_to "/#{user.nickname}"
    session[:user_id] = user.uid
  end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @github_user = GithubUser.new(current_user)
  end

  def index
    @github_user = GithubUser.new(current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_user_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="navbar-center">
    <%= link_to image_tag('octocat.png', class: 'icon-image'), users_path %>
    <form class="form-inline">
      <input class='search-bar' type="search" placeholder="Search Github" />
    </form>
    <ul class="navbar-nav">
      <%= link_to 'Pull Requests', '#', class: 'nav-link' %>
      <%= link_to 'Issues', '#', class: 'nav-link' %>
      <%= link_to 'Marketplace', '#', class: 'nav-link' %>
      <%= link_to 'Explore', '#', class: 'nav-link' %>
    </ul>
  </div>
  <ul class="nav navbar-right">
    <%= link_to image_tag(current_user.image, class: 'button-image'), "#{current_user.nickname}" %>
    <%= link_to 'Log Out', logout_path, class: 'nav-link' %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <%= render 'layouts/user_navbar' %>
    <% end %>

    <main class="main-page">

      <%= yield %>
    </main>
  </body>
</html>

app/views/users/index.html.erb
<div class="feed-container">
  <h4>Browse Activity</h4>
  <% @github_user.activity_events.each do |event| %>
  <figure class="feed-card">
    <%= image_tag event.user_avatar, class: 'avatar-image' %>
    <p><%= event.summary %></p>
    <p><%= distance_of_time_in_words(Time.now, event.created_at) %> ago</p>
  </figure>
  <% end %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Your Repositories <%= @github_user.repo_count %></th>
    </tr>
  </thead>
  <tbody>
    <% @github_user.repos.each do |repo| %>
    <tr>
      <td><%= link_to repo.name, repo.html_url %></td>
    </tr>
    <% end %>
  </tbody>
</div>

app/views/users/show.html.erb
<section class="user-info">
  <%= image_tag current_user.image, class: 'profile-image' %>
  <h1><%= current_user.name %></h1>
  <h2 class="heading-2"><%= @github_user.nickname %></h2>
  <p><%= current_user.bio %></p>
  <p><%= image_tag 'location-icon.png', class: 'small-icon-image' %><%= current_user.location %></p>
  <%= image_tag 'mail-icon.png', class: 'small-icon-image' %><%= mail_to current_user.email %>
  <% unless @github_user.organizations.empty? %>
    <h4>Organizations</h4>
    <div class="organizations">
      <% @github_user.organizations.each do |org| %>
        <%= image_tag org.avatar_url, alt: org.name, class: 'icon-image' %>
      <% end %>
    </div>
  <% end %>
</section>

<section class="repo-info container-fluid">
  <div class="row">
    <nav class="profile-navbar">
      <%= button_to 'Overview', '#', class: 'profile-nav-link', method: 'get' %>
      <%= button_to "Repositories #{current_user.repo_count}", "/#{current_user.nickname}?tab=repositories", class: 'profile-nav-link', method: 'get' %>
      <%= button_to "Stars #{@github_user.starred_repos.count}", '#', class: 'profile-nav-link', method: 'get' %>
      <%= button_to "Followers #{current_user.follower_count}", '#', class: 'profile-nav-link', method: 'get' %>
      <%= button_to "Following #{current_user.following_count}", '#', class: 'profile-nav-link', method: 'get' %>
    </nav>
  </div>
  <br /><p>Pinned respositories</p>
  <div class="pinned-repo-container">
    <% @github_user.pinned_repos.each do |repo| %>
      <figure class="pinned-repo">
        <h4><%= link_to repo.name, repo.html_url %></h4>
        <p><%= repo.language %></p>
      </figure>
    <% end %>
  </div>

  <br /><p>Contribution Activity</p>

  <div class="activity-feed">
    <h4>Created <%= pluralize(@github_user.recent_commits, "commit") %> in <%= pluralize(@github_user.recent_repo_commits.count, "repository") %></h4>
    <% @github_user.recent_repo_commits.each do |repo_name, commit_count| %>
    <p>
      <%= link_to repo_name, "https://github.com/#{repo_name}"%>
      <%= pluralize(commit_count, "commit") %>
    </p>
    <% end %>
  </div>
</section>

app/views/welcome/index.html.erb
<%= link_to 'Sign In with Github', '/auth/github' %>